---
- name: Disable SELinux
  selinux:
    state: disabled

- name: Stop & disable firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: no

- name: Enable ssh password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication '
    line: PasswordAuthentication yes
  notify:
    - restart ssh_service

- name: Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: docker installation
  include: docker.yaml
  
- name: kubernetes installation
  include: kubernetes.yaml
