- name: Initialize the Kubernetes cluster using kubeadm
  command: kubeadm init --apiserver-advertise-address="{{apiserver_ip}}" --node-name="{{node_name}}" --pod-network-cidr="{{network_pod_ip}}"

- name: Setup kubeconfig for vagrant user
  command: "{{ item }}"
  with_items:
  - mkdir -p /home/vagrant/.kube
  - cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
  - chown vagrant:vagrant /home/vagrant/.kube/config

- name: Copy kubeconfig to local file
  fetch: 
    src: /etc/kubernetes/admin.conf 
    dest: ./admin.conf
    flat: yes

- name: Install calico pod network
  command: kubectl create -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
  become: false

- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_command

- name: Copy join command to local file
  local_action: copy content="{{join_command.stdout_lines[0]}}" dest="./join-command"
  become: false
